resources:
  - name: docker-repo
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      paths: [Dockerfile]
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: docker_image
    type: docker-image
    source:
      repository: {{container_fullname}}
      email: {{docker_mail}}
      username: {{docker_user}}
      password: {{docker_password}}
      cache: true

  - name: github_release
    type: github-release
    source:
      user: {{github_user}}
      repository: {{git_repo}}
      access_token: {{github_token}}

jobs:
  - name: docker-terraform-release
    serial: true
    plan:
      - get: docker-repo
        trigger: true
      - put: docker_image
        params:
          build: docker-repo
          tag: docker-repo/version
          tag_as_latest: true
      - put: github_release
        params:
          name: docker-repo/version
          tag: docker-repo/version